accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import *

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(template_name = 'accounts/login.html'),name= 'login'),
    path('logout/', LogoutView.as_view(template_name = 'accounts/logout.html'),name= 'logout'),
    path('register/', UserCreateView.as_view(), name= 'register'),
    path('register/done/', UserCreateDoneTV.as_view(), name='register_done'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('accounts/', include('accounts.urls')),
]

photo/urls.py
from django.urls import path
from .views import *
app_name = "photo"

urlpatterns = [
    path("create/", PhotoCreate.as_view(), name='create'),
    path("like/<int:photo_id>/", PhotoLike.as_view(), name='like'),
    path("favorite/<int:photo_id>/", PhotoFavorite.as_view(), name='favorite'),
    path("delete/<int:pk>", PhotoDelete.as_view(), name='delete'),
    path("update/<int:pk>", PhotoUpdate.as_view(), name='update'),
    path("detail/<int:pk>", PhotoDetail.as_view(), name='detail'),
    path("like/", PhotoLikeList.as_view(), name="like_list"),
    path("favorite/", PhotoFavoriteList.as_view(), name="favorite_list"),
    path("mylist",PhotoMyList.as_view(), name="mylist"),
    path("", PhotoList.as_view(), name='index'),

]

from django.conf.urls.static import static

from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

photo/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to= 'timeline_photo/%Y/%M/%d')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    like = models.ManyToManyField(User, related_name='like_post', blank= True)
    favorite = models.ManyToManyField(User, related_name='favorite_post', blank= True)


    def __str__(self):
        return "text : "+self.text

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        return reverse('photo:detail', args=[self.id])

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic.base import TemplateView
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

# Create your views here.
class UserCreateView(CreateView):
    template_name = 'accounts/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('accounts:register_done')

class UserCreateDoneTV(TemplateView) :
    template_name = 'accounts/register_done.html'

photo/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from .models import Photo
from django.http.response import HttpResponseRedirect
from django.contrib import messages
from django.views.generic.base import View
from django.http import HttpResponseForbidden
from urllib.parse import urlparse


class PhotoList(ListView):
    model = Photo
    template_name_suffix = '_list'


class PhotoCreate(CreateView):
    model = Photo
    fields = ['author', 'text', 'image']
    template_name_suffix = '_create'
    success_url = '/'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            # 올바르다면
            # form : 모델폼
            form.instance.save()
            return redirect('/')
        else:
            # 올바르지 않다면
            return self.render_to_response({'form': form})

class PhotoUpdate(UpdateView):
    model = Photo
    fields = ['author', 'text', 'image']
    template_name_suffix = '_update'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs) :
        object = self.get_object()
        if object.author != request.user :
            messages.warning(request, '수정할 권한이 없습니다.')
            return HttpResponseRedirect('/')
        else :
            return super(PhotoUpdate, self).dispatch(request, *args, **kwargs)

class PhotoDelete(DeleteView):
    model = Photo
    template_name_suffix = '_delete'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs) :
        object = self.get_object()
        if object.author != request.user :
            messages.warning(request, '삭제할 권한이 없습니다.')
            return HttpResponseRedirect('/')
        else :
            return super(PhotoDelete, self).dispatch(request, *args, **kwargs)

class PhotoDetail(DetailView):
    model = Photo
    template_name_suffix = '_detail'

#좋아요 view
class PhotoLike(View) :
    def get(self, request, *args, **kwargs) : #get 방식으로 왔을 때
        if not request.user.is_authenticated : #로그인 확인
            return HttpResponseForbidden(); #자료 숨기기
        else :
            if 'photo_id' in kwargs : 
                photo_id = kwargs['photo_id'] #photo_id를 확인
                photo = Photo.objects.get(pk=photo_id) #primary key 가지도록
                user = request.user 
                if user in photo.like.all() : #이미 user가 좋아요 한 사람에 있으면
                    photo.like.remove(user) #클릭했을 때 지움
                else : #user 가 좋아요 아직 안눌렀으면
                    photo.like.add(user) #유저 추가
            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)

class PhotoFavorite(View) :
    def get(self, request, *args, **kwargs) :
        if not request.user.is_authenticated :
            return HttpResponseForbidden()
        else :
            if 'photo_id' in kwargs :
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk = photo_id)
                user = request.user
                if user in photo.favorite.all() :
                    photo.favorite.remove(user)
                else :
                    photo.favorite.add(user)
            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)

class PhotoLikeList(ListView):
    model = Photo
    template_name = 'photo/photo_list.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.warning(request, '로그인을 먼저 하세요')
            return HttpResponseRedirect('/')
        return super(PhotoLikeList,self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        #my like list
        user = self.request.user
        queryset = user.like_post.all()
        return queryset

class PhotoFavoriteList(ListView):
    model = Photo
    template_name = 'photo/photo_list.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.warning(request, '로그인을 먼저 하세요')
            return HttpResponseRedirect('/')
        return super(PhotoFavoriteList,self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        #my like list
        user = self.request.user
        queryset = user.favorite_post.all()
        return queryset

class PhotoMyList(ListView):
    model = Photo
    template_name = 'photo/photo_mylist.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.warning(request, '로그인을 먼저 하세요')
            return HttpResponseRedirect('/')
        return super(PhotoMyList,self).dispatch(request, *args, **kwargs)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="'col-6">
        <div class="alert alert-primary" role="alert">
            Please enter your login information. </div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="login" class = 'btn btn-outline-primary'>
        </form>
    </div>
    <div class="col"></div>

</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="'col-6">
        <div class="alert alert-primary" role="alert">
            로그아웃이 잘 되었습니다. </div>
        <a href="{% url 'accounts:login' %}" class="btn btn-outline-success">login 하기</a>
    </div>
    <div class="col"></div>

</div>
{% endblock %}

accounts/templates/accounts/register.html
{%extends "base.html" %}
{%load widget_tweaks%}

{%block title%}register.html{%endblock%}

{%block content%}

<div class="row">
    <div class="col"></div>
    
    <div class="'col-6">

        <h1>회원가입</h1>
        <p>ID와 비밀번호를 입력하세요. 비밀번호는 두 번 입력해야합니다.</p>
    
        {%if form.errors %}
        <div class="alert alert-danger">
            <div class="font-weight-bold">아래에 나타난 오류를 해결해주세요!</div>
            {{form.errors}}
        </div>
        {%endif%}
    
        <form action="." method="POST" class="card pt-3"> {%csrf_token%}
            <div class="form-group row">
                {{ form.username|add_label_class:"col-form-label col-sm-auto ml-3 font-weight-bold"}}
            </div>
    
            <div class="col-sm-5">
                {{ form.username|add_class:"form-control"|attr:"autofocus"}}
            </div>
    
            <div class="form-group row">
                {{form.password1|add_label_class:"col-form-label col-sm-auto ml-3 font-weight-bold"}}
            </div>
    
            <div class="col-sm-5">
                {{ form.password1|add_class:"form-control"}}
            </div>    
            
            <div class="form-group row">
                {{form.password2|add_label_class:"col-form-label col-sm-auto ml-3 font-weight-bold"}}
            </div>
    
            <div class="col-sm-5">
                {{ form.password2|add_class:"form-control"}}
            </div>
    
            <div class="form-group">
                <div class="offset-sm-9 col-sm-auto">
                    <input type="submit" value="sign up" class="btn btn-info"/>
                </div>
            </div>
        </form>
    </div>
    
    <div class="col"></div>

</div>

{%endblock%}

accounts/templates/accounts/register_done.html
{%extends 'base.html' %}
{%load widget_tweaks%}

{%block title%} register_done.html {%endblock%}

{%block content%}

<div class="row">
    <div class="col"></div>
    <div class="'col-6">
        <div class="alert alert-primary" role="alert">회원가입이 성공적으로 완료되었습니다!</div>
        <br>
        <p> 가입해주셔서 감사합니다.</p>
        <p class="font-italic"><a href="{% url 'accounts:login' %}">Login</a></p>
    </div>
    <div class="col"></div>
</div>

{%endblock%}

photo/templates/photo/photo_create.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <div class="alert alert-primary" role="alert">
            모든 부분을 다 채워넣어주세요!!
        </div>
        <form action="" method="post" enctype='multipart/form-data'>
            {% csrf_token %}

            {{form.as_p}}
            <input type="submit" value="Upload" class="btn btn-primary">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

photo/templates/photo/photo_delete.html
{% extends 'base.html' %}
{% block content %}
<!--진짜 지울건지 확인을 받아야 한다. form을 또 보여줄 필요가 없다.-->
<div class="alert alert-primary" role="alert">
  진짜로 {{object}}를 지우실 건가요?
</div>
<form action="" method ="post">
    {% csrf_token%}
    <input type="submit" value="Delete OK">
</form>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-4 col-md-4">
        <div class="card" style="width: 30rem">
            <img src=" {{ object.image.url }}" class="card-img-top" alt="...">
            <div class="card-body">

                <h5 class="card-title">{{ object.author }}</h5>
                <p class="card-text">{{ object.text }} </p>
            </div>
            <ul class="list-group list-group-flush">
                
                <li class="list-group-item">수정일 : {{ object.updated }}</li>
                <li class="list-group-item">생성일 : {{ object.created }}</li>
            
            </ul>
            <div class="card-body">
                <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>
            </div>
        </div>
    </div>

    <div class="col"></div>
</div>
{% endblock %}

photo/templates/photo/photo_list.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}

<div class='container'>
    <div class="row">
        <div class="col"></div>
        <div class="col-5">
            {%  for object in object_list %} 

            <div class="card">
                <div class="card-header">
                    {{ object.author }}
                </div>
                <img src=" {{ object.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <p class="card-text"> {{ object.text }} </p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <a href="{% url 'photo:like' object.id %}"
                                    class ="float-left btn-like
                                    {% if user in object.like.all %} active
                                    {% endif %}">좋아요!</a>
                        
                        {% if object.like.all.count %}
                        <span class="float left">
                            {{object.like.all.count}}
                        </span>
                        {%endif%}
                        <a href="{% url 'photo:favorite' object.id %}"
                                    class ="float-left btn=-favorite
                                    {% if user in object.like.all %} active
                                    {% endif %}">저장하기!</a>
                    </li>
                    <li class="list-group-item">생성일 : {{ object.created }}</li>
                    <li class="list-group-item">수정일 : {{ object.updated }}</li>
                </ul>
                <div class="card-body">
                    <!--<a href="{% url 'photo:detail' object.id %}" class="card-link">댓글달기</a> -->
                    <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                    <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>

                </div>

            </div>
            {% endfor %}

        </div>
        <div class="col">
            {% if user.is_authenticated %}
            {% load static %}
            <div class="card" style="">
                <img src="{% static 'images/profile.jpg' %}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{user.username}}</h5>
                    <p class="card-text">회원님의 게시물을 확인해보세요!</p>
                    <a href="{% url 'photo:mylist' %}" class="btn btn-primary">MYPAGE 이동</a>
                </div>
            </div>
            {% else %}
            {% load static %}
            <div class="card" style="">
                <img src="{% static 'images/unknown.jpg' %}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">unknown</h5>
                    <p class="card-text">회원님의 게시물을 확인해보세요!</p>
                    <a href="{% url 'photo:mylist' %}" class="btn btn-primary">MYPAGE 이동</a>
                </div>
            </div>

        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

photo/templates/photo/photo_mylist.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<style>

</style>

<div class="row">
   <div class="col-md-12">
       <div id="mdb-lightbox-ui"></div>
       <div class="mdb-lightbox no-margin">
           <div class="row">
               {% for object in object_list %} <!-- 객체 가져오기-->
               {% if object.author == request.user %} <!-- 작성자 같아야 가져오기-->
               <figure class="col-md-4">
                   <div style="width: 18rem;">
                       <img src="{{object.image.url}}" class="card-img-top" alt="...">
                   </div>
               </figure>
               {% endif %}
               {% endfor %}
           </div>
       </div>
       <div class="col"></div> <!--로그인 리스트-->
   </div>
</div>

{% endblock %}

photo/templates/photo/photo_update.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Create">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}